### ISSUE TITLE
Not working on 1.17.0

### ISSUE THREAD

**Issue by davidmondok** [mrmlnc/vscode-postcss-sorting#76] opened 2017-10-10 21:10 UTC
Hi,

since the update to the latest VSCode Version1.17.0, sorting doesn't work. Nothing happens on command execution. I tried sorting with default settings, with a json file containing settings or adding them to the settings.json but had no success in either case. Tried it with both css and scss files.

Anybody else experiencing the same problem?

cheers

**Comment by simon-nguyen-r2r** [comment] 2017-10-10 22:47
I'm having the same issue, on Windows and VSCode V 1.17.1

**Comment by mrmlnc** [comment] 2017-10-11 05:51
Hello, @genmacg, @simtechmedia,

Works fine for me with settings from `postcss-sorting` repository and simple CSS file.

**.postcss-sorting.json**:

```json
{
    "properties-order": [
        "margin",
        "padding",
        "border",
        "background"
    ]
}
```

**file.css**:

```css
body {
	line-height: 1.5;
	margin: 1px;
}
```

Please, provide more details for your case.

**Comment by davidmondok** [comment] 2017-10-11 11:00
Hi,

I seem to have used a version, that was still relying on post-css sorting 2.x. In version 3 property groups were removed, which I still had in my config file.

Config for 2.x:

```
{
	"properties-order": [
		{
			"properties": [
				"margin",
				"padding"
			]
		},
		{
			"emptyLineBefore": true,
			"properties": [
				"border",
				"background"
			]
		}
	]
}
```

Config for 3.x:

```
{
	"properties-order": [
		"margin",
		"padding",
		"border",
		"background"
	]
}
```

**Comment by davidmondok** [comment] 2017-10-11 11:12
My question might be misplaced here, but do you know how I can work around the removal of this feature so I can properly add new lines before my property groups without a hassle?

**Comment by mrmlnc** [comment] 2017-10-11 11:15
I don't fully understand your problem. You can disable auto update for extensions and use latest release with [`postcss-sorting@2.x.x`](https://github.com/mrmlnc/vscode-postcss-sorting/releases/tag/2.3.0). Just install extension from `.vsix` file.

**Comment by davidmondok** [comment] 2017-10-11 14:58
Sometimes it's hard to understand dummies because we assume they have the same information as us :-) I'm gonna be upfront, I had no idea about any of the things you just explained. But thx a bunch mate, you solved my problem perfectly ^^

**Comment by MrSauceman** [comment] 2017-10-16 14:50
I get an error every time I run postcss sorting on vscode 1.17.1.

I have uninstalled the plugin and reinstalled it and reset the config settings to default, and tried multiple different config settings for 3.x.  I don't even think it is getting to the point where it reads the config settings.

Here is the error:
````
"Error: Running the contributed command:'postcssSorting.execute' failed.
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:348465)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:444633)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:290588)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:290278)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:289305
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:291224
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:58570
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57853)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:59575)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:107349)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)"
````

**Comment by mrmlnc** [comment] 2017-10-16 14:52
@MrSauceman, you can provide GIF for your case?

**Comment by MrSauceman** [comment] 2017-10-16 14:54
@mrmlnc Does this error not happen for you on 1.17.1?  All I did is install the plugin and run it on a css file and this error comes up every time.

**Comment by mrmlnc** [comment] 2017-10-16 14:59
Nope. I cannot reproduce this situation :(

![screencast 2017-10-16 17-57-40](https://user-images.githubusercontent.com/7034281/31618812-9d861152-b29b-11e7-8c66-075f64362b1b.gif)

**Comment by MrSauceman** [comment] 2017-10-16 14:59
You are on 1.17.1 there?

**Comment by mrmlnc** [comment] 2017-10-16 15:00
Yeap, VS Code, macOS, Version 1.17.1 (1.17.1).

**Comment by MrSauceman** [comment] 2017-10-16 15:02
Windows for me.  I wish I had more information, I do exactly what you are doing in that gif, and all I get is that error and stack trace that I posted.

**Comment by mrmlnc** [comment] 2017-10-16 15:06
I want to see your workspace and how to you run command (for example with data from my comment above). Any way:

  * You run command without opened workspace? Or with?
  * You try to use my extension without other plugins?
  * You can give me list of your extensions?

**Comment by MrSauceman** [comment] 2017-10-16 15:11
That helped me try something.

I was running this in a single file without a workspace open and I was getting that error.  When I opened a project folder and then ran the command on one of the files within the project, it worked perfectly.  Then, I created a new file and changed the language to css and it fails with the error I posted above.

Seems to only work on a file that is part of an open workspace?

**Comment by mrmlnc** [comment] 2017-10-16 15:13
> Seems to only work on a file that is part of an open workspace?

Yeap. It's True. Will be fixed today.

**Comment by MrSauceman** [comment] 2017-10-16 15:15
Nice, I'm glad we found the problem.

Also, when I created the new file and the sorting didn't work, I then saved the file into my open workspace and tried the command again, and it still failed.  It was only after I closed this file and then reopened it that it started working.

Hope that helps!

**Comment by mrmlnc** [comment] 2017-10-17 06:52
Should be fixed by `3.0.1`, please try this version 🎉

**Comment by MrSauceman** [comment] 2017-10-17 14:04
Yes, it works!  Awesome.  Thank you.

**Comment by mrmlnc** [comment] 2017-10-17 14:14
Thanks for clarification and debug 🌮

**Closed as completed by mrmlnc** 2017-10-17 14:14 UTC
Labels: Type: Need More Details, Priority: Low

**Comment by Lefthandmedia** [comment] 2023-08-14 09:43
So does this mean this extension doesn't work anymore? is it a dead project?
