### ISSUE TITLE
Question: Any plans to use PostCSS Sorting 2.x.x anytime soon?

### ISSUE THREAD

**Issue by pawelgrzybek** [mrmlnc/vscode-postcss-sorting#41] opened 2017-01-16 16:58 UTC
⬆️   ⬆️   ⬆️   ⬆️   ⬆️   ⬆️

Thanks 😊

**Comment by mrmlnc** [comment] 2017-01-16 17:23
Thanks for reporting I'll update this plugin today😅

Closed as duplicate of https://github.com/mrmlnc/vscode-postcss-sorting/issues/40

**Closed as completed by mrmlnc** 2017-01-16 17:23 UTC
